version: '3'
# Список наших сервисов (контейнеров)
services:
    nginx:
        container_name: nginx_rabbitmq
        image: nginx:latest
        # mapping ports
        ports:
            - "85:80"
            - "86:82"
        # mapping directories
        volumes:
            - ./nginx:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
        depends_on:
          - php_sender
        restart: always

    php_sender:
        container_name: php_rabbitmq_sender
        # directory for php dockerfile
        build: ./php_instances/php_sender
        
        #depends_on:
          #- elastic_search
        volumes:
            - ./www/sender:/var/www/sender
        restart: always
    
    php_receiver:
        container_name: php_rabbitmq_receiver
        build:
          context: .
          dockerfile: php_instances/php_receiver/Dockerfile
        command: "php index.php"
        volumes:
          - ./www/php_receiver:/var/www/php_receiver
        depends_on:
          rabbitmq:
            condition: service_healthy
        restart: always
      
    python:
        container_name: python
        build:
          context: .
          dockerfile: python/Dockerfile
        depends_on:
          - rabbitmq
          #- elastic_search
        tty: true
        ports:
          - 8000:8000
        #command: 'python index.py runserver 0.0.0.0:8000'
        volumes:
          - ./www/python:/var/www/python
        restart: always
        
    rabbitmq:
      container_name: rabbitmq
      build:
        context: .
        dockerfile: rabbitmq/Dockerfile
      ports:
        - "15672:15672"
        - "5672:5672"
      restart: always
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

    #ElasticSearch
   

         
